spring.application.name=gym-back

server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/gym_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Kolkata
spring.datasource.username=root
spring.datasource.password=bhartesh8

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

app.jwt.secret=GymApplicationSecretKey2026VeryLongSecretKeyForJwtSigning123456789

app.jwt.expiration=86400000